### ISSUE TITLE
Pinot datasets not showing in thirdye UI

### ISSUE THREAD

**Issue by ShubhamMMT1** [apache/incubator-pinot#4334]
I have integrated pinot into thirdeye using following connector configurations-
- className: com.linkedin.thirdeye.datasource.pinot.PinotThirdEyeDataSource
    properties:
        zookeeperUrl: 'localhost:2181'
        clusterName: 'PinotCluster'
        controllerConnectionScheme: 'http'
        controllerHost: '10.30.106.42'
        controllerPort: 9000
        cacheLoaderClassName: com.linkedin.thirdeye.datasource.pinot.PinotControllerResponseCacheLoader
    metadataSourceConfigs:
      - className: com.linkedin.thirdeye.auto.onboard.AutoOnboardPinotMetadataSource

  - className: org.apache.pinot.thirdeye.datasource.sql.SqlThirdEyeDataSource
    properties: ......

The pinot is working fine on 9000 port.  I ingested data into pinot using the offline mode. I am able to query as well on the pinot server. But the data doesn't appear in the root cause analysis.
I also checked the admin dashboard. The data doesn't appear in the database configuration.
Moreover auto onboarding of the pinot datasets in the thirdye-frontend/config/detector.yml file
is also set to true.  Any solutions to this??

**Comment by akshayrai** [comment]
@ShubhamMMT1 can you share the events you see in the logs? Any error or warning messages?

**Comment by ShubhamMMT1** [comment]
ERROR [2019-06-19 06:36:26,339] org.apache.pinot.thirdeye.datasource.DataSourcesLoader: Exception in creatingthirdeyedatasourceorg.apache.pinot.thirdeye.datasource.sql.SqlThirdEyeDataSource ! java.lang.IllegalStateException: The file is locked: nio:/home/shubham.mourya/third/incubator-pinot/thirdeye/thirdeye-pinot/config/h2db.mv.db [1.4.192/7]

This is what I am getting in the logs of run-backend.sh.

**Comment by ShubhamMMT1** [comment]
ERROR org.apache.pinot.thirdye.auto.onboard.AutoOnboardUtility: Exception in creating metadata.constructor.com.linkedin.thirdeye.auto.onboard.AutoOnBoardPinotMetaDatasoorce
Warn -java.lang.ClassNotfoundException- cm.linkedin.thirdeye.auto.onboard.AutoOnboardPinotMetaDataSource


Shows class not found as well! @akshayrai  Soln to these?

**Comment by akshayrai** [comment]
There is a bug in the documentation. It should be `org.apache.pinot.thirdeye.auto.onboard.AutoOnboardPinotMetadataSource` and `org.apache.pinot.thirdeye.datasource.pinot.PinotThirdEyeDataSource` instead of `com.linkedin.thirdeye...` (Notice the package name)

@ShubhamMMT1 , have you resolve the SqlThirdEyeDataSource issue?

**Comment by ShubhamMMT1** [comment]
Yes, it  was resolved. The class name was incorrect.
Thanks @akshayrai

**Comment by zhixun-luy** [comment]
```
# Please put the mock data source as the first in this configuration.
dataSourceConfigs:
  - className: org.apache.pinot.thirdeye.datasource.pinot.PinotThirdEyeDataSource
    properties:
      zookeeperUrl: 'localhost:2181'
      clusterName: 'PinotCluster'
      controllerConnectionScheme: 'http'
      controllerHost: '127.0.0.1'
      controllerPort: 9000
      cacheLoaderClassName: org.apache.pinot.thirdeye.datasource.pinot.PinotControllerResponseCacheLoader
    metadataSourceConfigs:
      - className: org.apache.pinot.thirdeye.auto.onboard.AutoOnboardPinotMetadataSource
```
 I used this configuration, and got an error.
```
2022-05-17 18:26:33.104 [main] INFO  org.apache.pinot.thirdeye.datalayer.util.DaoProviderUtil - Using existing database at 'jdbc:mysql:///thirdeye?autoReconnect=true'
May 17, 2022 6:26:37 PM org.apache.tomcat.jdbc.pool.ConnectionPool init
SEVERE: Unable to create initial connections of pool.
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
```
@akshayrai @ShubhamMMT1 
Do you have any suggestion for this error?
