### ISSUE TITLE
logback.xml is not honored

### ISSUE THREAD

**Issue by tannaga** [apache/incubator-pinot#4966]
When i run the `./run-frontend.sh` script, logs coming from the `thirdeye-pinot` folder does not seem to reflect settings in 
`https://github.com/apache/incubator-pinot/blob/master/thirdeye/thirdeye-pinot/src/main/resources/logback.xml`

Looks like somewhere in the class loader path, there is a different logger instantiated.

Is there something I am missing?

**Comment by tannaga** [comment]
I resolved this.  Dropwizard logging overloads other configuration.
I am able to control it in `config/detector.yml` and `config/dashboard.yml`
Ex:
```
logging:
  level: INFO
  loggers:
    org.hibernate.engine.internal: WARN
    org.apache.pinot.thirdeye: DEBUG
```
May be adding a note in the logback.xml  would surely help first time developers
