### ISSUE TITLE
Don't lose authority portion of inputDirURI when creating output files

### ISSUE THREAD

**Issue by kkrugler** [apache/incubator-pinot#6355]
Assume you have a job spec file with:

``` yml
inputDirURI: 'hdfs://<clustername>/user/hadoop/pinot-input/'
includeFileNamePattern: 'glob:**/us_*.gz'
outputDirURI: 'hdfs://<clustername>/user/hadoop/pinot-segments/'
```

During the job, you'll get this error for every segment generated:

```
Failed to generate Pinot segment for file - hdfs:/user/hadoop/pinot-input/us_2020-03_03.gz
java.lang.IllegalStateException: Unable to extract out the relative path based on base input path: hdfs://<clustername>/user/hadoop/pinot-input/
```

The problem is that `SegmentGenerationJobRunner.getFileURI()` generates input file URIs that no longer have the authority portion of the original `inputDirURI`.
