### ISSUE TITLE
Support environment variable injection via Pinot helm chart.

### ISSUE THREAD

**Issue by mikecdavis-dd** [apache/incubator-pinot#6815]
The current Pinot helm chart does not provide a way to inject custom environment variables. Environment variables can be used as a substitute for config properties as well as templated table definitions and is already supported as part of the Pinot runtime.

Specifically we need to inject secrets for Pinot Basic Auth https://github.com/apache/incubator-pinot/pull/6613 as well custom Kafka credentials via table config [overrides](https://docs.pinot.apache.org/configuration-reference/table#environment-variables-override).

## Proposal
Add support for both `envFrom` and `extraEnv` for each statefulset. `envFrom` is useful for batch inject env from existing secrets or configMaps, while `extraEnv` can be used to add individual key values.

Example override:
```yaml
server:
  envFrom:
    - secretRef:
        name: my-secrets
  extraEnv:
    - name: PINOT_CUSTOM_ENV_1
      value: my-value-1
    - name: PINOT_CUSTOM_ENV_2
      value: my-value-2
```
